CREATE TABLE MART1 (
    Period DATETIME,
    Number VARCHAR(255),
    pNumber VARCHAR(255),
    ct DECIMAL(10, 1),
    sumrub DECIMAL(10, 1),
    sumdol DECIMAL(10, 2),
    ssdol DECIMAL(10, 2),
    qty DECIMAL(10, 1),
    group_customer VARCHAR(255),
    brand VARCHAR(255),
    tovtype VARCHAR(255),
    tovsubtype VARCHAR(255),
    salesdep VARCHAR(255),
    Sales_manager VARCHAR(255),
    client VARCHAR(255),
    city VARCHAR(255),
    clienttype VARCHAR(255),
    sklad VARCHAR(255),
    nomenklatura VARCHAR(255),
    Product_manager VARCHAR(255),
    product_type VARCHAR(255),
    GroupName VARCHAR(255),
    ClientTypeName VARCHAR(255),
    rentabelnost DECIMAL(10, 10)
);
